### ISSUE TITLE
Release for 3.0.0-M2

### ISSUE THREAD

**Issue by SethTisue** [scala/nanotest-strawman#106]
currently the crossbuild is for 0.27.0-RC1, so it's probably pretty close

**Comment by SethTisue** [comment]
@eed3si9n did you say something on Twitter about there being some kind of blocker here...?

**Comment by eed3si9n** [comment]
verify is back published to both M1 and M2 - https://repo1.maven.org/maven2/com/eed3si9n/verify/verify_3.0.0-M2/0.2.0/
but when I tried to use it Dotty seemed to now like it - https://github.com/lampepfl/dotty/issues/10544
