### ISSUE TITLE
publish `verify_native0.4_3`

### ISSUE THREAD

**Issue by xuwei-k** [scala/nanotest-strawman#181]

**Comment by eed3si9n** [comment]
Should I wait till Scala Native 0.4.3 final comes out?

**Comment by JD557** [comment]
It's out now.
Note that scala native is not compatible with 3.0.x, only 3.1.x, so this will need some changes to the crossbuild.

**Comment by eed3si9n** [comment]
Thanks guys. It's out - https://repo1.maven.org/maven2/com/eed3si9n/verify/verify_native0.4_3/1.0.0/
