### ISSUE TITLE
power assertion

### ISSUE THREAD

**Issue by eed3si9n** [scala/nanotest-strawman#2]
power assertion is a popular idea among Lightbend Scala team and core contributors.

But there's a concern brought up by @bvenners

> On power assertions, I would think we'd want to avoid macros to keep it simple, just have plain old assertions, at least until only Scala 3 is supported. Until then you'll need to write it twice, once for Scala 2 and again for Scala 3.
>
> What build tool or tools do all the compiler projects use when they want to run their tests? Do they use sbt, maven, something else?

**Comment by Ichoran** [comment]
This is a general problem for any sort of tooling having to do with the code, not just a minimal test framework.  It would be nice if Scala would support some basic who-am-I-and-what-am-I-doing directives by providing implicits that quote, say, the current expression or line, and things line line numbers.  Basically the stuff that [sourcecode](https://github.com/lihaoyi/sourcecode) already does, but internalized into the compiler so it doesn't have to rely upon macros.

**Comment by eed3si9n** [comment]
Bill said we have to write power assertion twice, but there are several implementations for Scala 2 already - https://github.com/eed3si9n/expecty, ScalaTest, and uTest.
So if we want power assertion, the task would be to implement one for Dotty.

**Comment by Ichoran** [comment]
Again, if we're missing a key feature from the language I would say the right thing to do is add the feature(s) needed to make it possible (to both Dotty at 2.14) and have a common implementation, not have two different implementations.

**Comment by eed3si9n** [comment]
The ability to display something like the following:

```scala
> assert(person.say(word1, word2) == "pong pong")

/*
Output:

java.lang.AssertionError:

person.say(word1, word2) == "pong pong"
|      |   |      |      |
|      |   ping   pong   false
|      ping pong
Person(Fred,42)
*/
```

is not terribly complicated, but the feature needed for it I think boils down to traversing some captured tree, and generating code, so some form of macro. The exact implementation of it largely would depend on the details of the macro framework offered by Scala 2 or 3, I think.

**Comment by scf37** [comment]
There is old `expecty`, writen by Groovy author: https://github.com/pniederw/expecty
And my fork, a bit newer but still damn old: https://github.com/scf37/expecty

**Comment by Ichoran** [comment]
If you want it exactly like that, yes, you'd need to inspect the tree.

But if you have

```
(word1, word2) |> person.say =?= "pong pong"
```

then you only need very basic source introspection tools.  You'd write the test framework as something like (using fake implicit names):

```
implicit class ComputeTwoPipe[A, B](inputs: (A, B))(implicit inLit: LiteralArgs) {
  def |>[C](f: (A, B) => C)(implicit outLit: LiteralArgs) = ComputeTwo(inputs, f, inLit, outLit)
}

case class ComputeTwo[A, B, C](inputs: (A, B), f: (A, B) => C, inLit: LiteralArgs, outLit: LiteralArgs) {
  def =?=(expected: C)(implicit line: LineNumber, implicit expr: LiteralExpr) = {
    val result = f(inputs._1, inputs._2)
    val correct = result == expected
    if (!correct) {
      println(s"Failed test at $line in");
      println(s"  $expr");
      println(s"Inputs: $inLit == $inputs")
      println(s"Function: $outLit")
      println(s"Result: $result")
      println(s"Expected: $expected)
    }
    correct
  }
}
```

Given something that could give you the literal text of arguments, an expression, and a line number, that would be a complete solution, and a really useful one.  The syntax could change; I made it as close to what you wrote as possible.  But if we're willing to give up a little bit on AST parsing and make that be manual (so slightly less power), you can get a long way with only very basic capabilities to understand what the source was.

**Comment by Ichoran** [comment]
(I just returned a boolean value as a return and printed stuff out, but depending on how the framework works, you might want to cause some side effect or return something more elaborate.)

**Comment by eed3si9n** [comment]
@scf37 my expecty fork is kept relatively fresh, latest commit made yesterday - https://github.com/eed3si9n/expecty/commits/master

**Comment by eed3si9n** [comment]
The beauty of `assert(person.say(word1, word2) == "pong pong")` is that its user doesn't have to learn anything new, since the complexity is pushed into the implementation.

While I'm in agreement about the usefulness of source location macros (in fact Minitest implements one internally), I think it's somewhat independent issue from incorporating fully fledged power assertion macro, so I've created #7 to discuss it.

**Comment by non** [comment]
This is a pretty old issue, but I'll comment anyway.

My suggestion is to plan for a method to do this (maybe reserving a name) but don't make implementing it a requirement. Since the idea here is to be bare bones I don't think you need to implement it initially to make something useful.

**Comment by som-snytt** [comment]
This is a pretty old issue, but I'll comment anyway. 👍 for power asserts!

I don't even like to say `assert`. What else would I be doing? It's a test! My old version of the feature just let you say `inspect { body }` and the test tool finds the expressions to assert.

Another nice feature (come to think of it) would be verbose mode, that outputs what was asserted.

My colleague spent some time on asserts in Java that compare collections and decide dynamically whether to compare iteration order, for example. I was not entirely persuaded, because you never know what's being tested, but at least it should be a failure that surprises you. But now I'd actually like to be able to ask the test rig to show me in ascii art what it compared when the test passed.
