### ISSUE TITLE
name this library

### ISSUE THREAD

**Issue by eed3si9n** [scala/nanotest-strawman#3]
I suggested SUnit, but @Ichoran said

> I think we should stay as far away from the word `unit` as possible in case novice users encounter this.  `Unit` is very unlike `SUnit`; one is the canonical content-free return type, while the other would be a testing framework.  This can only provoke confusion.

so for now I've named this repo nanotest-strawman

**Comment by som-snytt** [comment]
"gene".

**Comment by Ichoran** [comment]
Why not "nanotest"?  You already named it that (I forget who suggested it and picotest first?) and it seems reasonable (if ends up as a very minimal test framework)!

**Comment by dwijnand** [comment]
* scala-testkit (kind of taken now)
* testkit
* scala-testlib
* scala-unit-test

**Comment by eed3si9n** [comment]
I'm fine with nanotest, as long as it's not perceived as a metric competition with μTest.

If we want to pick a cute dictionary word:
- cutest

**Comment by Ichoran** [comment]
I love cutest!  Probably not serious enough.  But I still love it.

**Comment by som-snytt** [comment]
For gravitas, simply pronounce it "see micro test".

**Comment by alexandru** [comment]
👍 on `cutest`

It doesn't have to be serious, it just has to be "safe for work" and memorable.

**Comment by kubukoz** [comment]
👍 on cutest, unless anyone has SEO doubts...

**Comment by dwijnand** [comment]
Cutest is cute, but it runs into the same risk that "simple build tool" ran into...

**Comment by eed3si9n** [comment]
@dwijnand I intend to be very cute, but if someone says this library is not cute enough, I take that to be a compliment.

**Comment by eed3si9n** [comment]
Some more alternatives out of a brainstorm:

- skeptic
- taquito
- pika
- verify
- qtest
- exam

**Comment by som-snytt** [comment]
Those are also cute.

If the purpose of tests is to restore faith in your code, then antiskeptic.

If to keep it clean, then antiseptic.

If the tests are monadic, then taquito is an easy way to explain it to beginners.

**Comment by eed3si9n** [comment]
I am starting to like `scala.verify` more.
Easy name to remember (I think), and it sort of states what it's going to do.

**Comment by SethTisue** [comment]
magpie, skylark, bureaucrat, testnik, flywheel, quixotic

**Comment by Ichoran** [comment]
`verify` is my favorite so far

**Comment by lrytz** [comment]
> bureaucrat

sbi (scala's bureau of investigation)

**Comment by SethTisue** [comment]
Trust, but verify.
