### ISSUE TITLE
Infix assertion-operator support

### ISSUE THREAD

**Issue by valenterry** [scala/nanotest-strawman#31]
For simple assertions, I like to use infix assertion syntax like how it is supported in utest with [arrow asserts](https://github.com/lihaoyi/utest#arrow-asserts):

```scala
val result = ???
val expected = ???
result ==> expected
```

I find this nicer to read as it visually separates variable names from the assert method.
The specific assertion method name is not as important, as long as it allows for visual separation and allows infix syntax imho.

**Comment by SethTisue** [comment]
my personal two cents:

in this library, I suggest we don't go down the road of having multiple, only cosmetically-different ways to do the same thing

also, I also think the bar for addition should be set especially high when the new identifier in question is symbolic. IMO the Scala library ecosystem (including stdlib) already has too many symbols flying around

**Comment by eed3si9n** [comment]
@valenterry Thanks for feedback!

I agree with Seth. Minitest was written specifically to [avoid DSLs](https://alexn.org/blog/2017/11/10/minitest-no-crap-scala-library.html), and we chose it as a basis for scala-verify because it has least amount of decorative things.

I am all for making the _implementation_ cute (look at power assertion etc), but I'd like the surface API to be spartan and minimal (everything that can be removed is removed).

**Comment by valenterry** [comment]
I see. I'm fine with defining such a custom operator for my own projects, however sometimes this is hard to impossible when macros are used, even though it is just an alias for the existing `assert` - I assume this is also the case here for the `assert` macro?

**Comment by eed3si9n** [comment]
You're right. `def apply(value: A): R` of the `assert` value takes one argument (https://github.com/scala/nanotest-strawman/blob/242ef579fca8a78fc483874858185d55049b1f1e/shared/src/main/scala-2/verify/asserts/Recorder.scala), so it's probably impossible to make an alias for it, but it's likely possible to reimplement two-argument macro following the example I did over the weekend for String diffing - https://github.com/scala/nanotest-strawman/blob/242ef579fca8a78fc483874858185d55049b1f1e/shared/src/main/scala-2/verify/asserts/AssertEqualsMacro.scala
