### ISSUE TITLE
Update to Dotty 0.19.0-RC1

### ISSUE THREAD

**Issue by alexander-myltsev** [scala/nanotest-strawman#36]
Please, update to Dotty 0.19.0-RC1 and publish the artifact

**Comment by SethTisue** [comment]
this isn't just a matter of bumping the version number and publishing: it needs code changes, as Dotty has changed

is there a volunteer who would like to tackle it...?

**Comment by TheElectronWill** [comment]
@SethTisue I'll give it a try!

**Comment by eed3si9n** [comment]
Note that https://github.com/lampepfl/dotty/issues/7189 is not fixed yet, so it might only work on my machine only.

**Comment by SethTisue** [comment]
PR: #37

**Comment by SethTisue** [comment]
this auto-closed; but I assume the actual publishing isn't done yet?

**Comment by pbvie** [comment]
Hello! Are there any blockers that prevent publishing this? :)

**Comment by eed3si9n** [comment]
I don't think so. I just need to remember to do it today.

**Comment by pbvie** [comment]
Thanks! :bowing_woman:

**Comment by eed3si9n** [comment]
For the record, here's what I've done to back publish current HEAD as 0.2.0 for Dotty 0.19:

```
clean
set ThisBuild / version := "0.2.0"
++0.19.0-RC1!
verifyJVM/publishSigned
```

Maven sync should happen shortly.

**Comment by SethTisue** [comment]
@eed3si9n publish for 0.20?

**Comment by eed3si9n** [comment]
I am getting bunch of errors with 0.20, so I have to look into it.
