### ISSUE TITLE
Request for Scala.js 1.0.0-RC1 and Scala Native 0.4.0-M2 support

### ISSUE THREAD

**Issue by ekrich** [scala/nanotest-strawman#42]
True cross platform support for testing libraries would be fabulous. I can almost get there with JUnit for JVM, Dotty, and Scala.js minus Scala Native.

I have a couple of tests for Scala Native via @lolgab 's published version of minitest for `0.3.9` and `0.4.0-M2` but would love to just have one basic testing lib.

**Comment by lolgab** [comment]
I opened a PR to test Scala Native 0.4.0-M2 in travis: https://github.com/scala/nanotest-strawman/pull/43

**Comment by SethTisue** [comment]
#43 is merged. someone want to PR the Scala.js version bump?

**Comment by lolgab** [comment]
Maybe my pull request was wrong.. It seems that Travis is not running on pull requests from forks. @SethTisue Can you check if it's the case?
I can take the Scala.js too 👍

**Comment by SethTisue** [comment]
Travis-CI appears to already be configured to run on pull requests:

<img width="228" alt="Screen Shot 2019-11-29 at 8 34 07 AM" src="https://user-images.githubusercontent.com/161079/69875544-09a44e00-1283-11ea-9713-1e9a2ff0add8.png">

I guess let's be extra-cautious with your next PR and make sure the right Travis stuff is happening before we merge it

**Comment by SethTisue** [comment]
@lolgab is there anything remaining to be done for Scala.js support? or do we close this ticket?

**Comment by eed3si9n** [comment]
I am seeing the same issue of Travis CI not running so I've split this up into a new issue #45.

**Comment by eed3si9n** [comment]
Back published 0.2.0 for all the platforms.
