### ISSUE TITLE
Travis CI is not running on pull requests

### ISSUE THREAD

**Issue by eed3si9n** [scala/nanotest-strawman#45]
Maybe my pull request was wrong.. It seems that Travis is not running on pull requests from forks. @SethTisue Can you check if it's the case?
I can take the Scala.js too 👍

_Originally posted by @lolgab in https://github.com/scala/nanotest-strawman/issues/42#issuecomment-559728443_

**Comment by eed3si9n** [comment]
I sent https://github.com/scala/nanotest-strawman/pull/44 but Travis CI didn't seem to trigger.

**Comment by eed3si9n** [comment]
Webhook seems to be delivering to https://notify.travis-ci.org.

**Comment by eed3si9n** [comment]
I wonder if this has something to do with "Travis CI" listed under "Installed GitHub Apps" under scala organization. This I think uses travis **.com** - https://travis-ci.com/scala/nanotest-strawman - but the job isn't triggered there either.

**Comment by dwijnand** [comment]
In the menu you can find the build requests: https://travis-ci.com/scala/nanotest-strawman/requests

![image](https://user-images.githubusercontent.com/344610/71662172-73af8780-2d48-11ea-9534-7cb25b8ef51e.png)

#46.

**Comment by eed3si9n** [comment]
Thanks @dwijnand!
