### ISSUE TITLE
source location / sourcecode macro

### ISSUE THREAD

**Issue by eed3si9n** [scala/nanotest-strawman#7]
> This is a general problem for any sort of tooling having to do with the code, not just a minimal test framework.  It would be nice if Scala would support some basic who-am-I-and-what-am-I-doing directives by providing implicits that quote, say, the current expression or line, and things line line numbers.  Basically the stuff that [sourcecode](https://github.com/lihaoyi/sourcecode) already does, but internalized into the compiler so it doesn't have to rely upon macros.

_Originally posted by @Ichoran in https://github.com/scala/nanotest-strawman/issues/2#issuecomment-512007994_

**Comment by eed3si9n** [comment]
I think we should lobby to get lihaoyi/sourcecode in-sourced into 2.14 + Dotty, and for 2.11 ~ 2.13 included into nanotest (aka cutest) module under some package name.

**Comment by alexandru** [comment]
@eed3si9n you don't have to import `sourcecode`, because you already have it:

https://github.com/scala/nanotest-strawman/blob/master/shared/src/main/scala/minitest/api/SourceLocation.scala

**Comment by alexandru** [comment]
Would be cool for this to get into Scala 2.14 and Dotty though.

**Comment by eed3si9n** [comment]
Yea. I am aware of the `SourceLocation`. So my thinking is that if we're going to have it as part of this effort anyway, we should pick the best one out there. There's been a number of occasions Scala team has discussed bringing in sourcecode, so I think this would be a good opportunity.
